<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.infiext.soybean</groupId>
        <artifactId>soybean</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>soybean-core</artifactId>
    <packaging>pom</packaging>
    <description>核心聚合模块</description>

    <modules>
        <module>core-common</module>
        <module>core-data</module>
        <module>core-web</module>
        <module>core-excel</module>
        <module>core-upload</module>
        <module>core-mail</module>
    </modules>
</project>