<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.infiext.soybean</groupId>
        <artifactId>soybean-extension</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>soybean-extension-upload</artifactId>
    <description>核心上传模块</description>

    <dependencies>
        <dependency>
            <groupId>com.infiext.soybean</groupId>
            <artifactId>soybean-core-common</artifactId>
        </dependency>

        <dependency>
            <groupId>com.infiext.soybean</groupId>
            <artifactId>soybean-core-data</artifactId>
        </dependency>

        <dependency>
            <groupId>com.infiext.soybean</groupId>
            <artifactId>soybean-core-excel</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.mybatis-flex</groupId>
            <artifactId>mybatis-flex-spring-boot3-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
        </dependency>
    </dependencies>
</project>
